id = "code-stats"
name = "Code::Stats"
description = "Tracks coding XP with Code::Stats."
version = "0.3.0"
schema_version = 1
authors = ["Marshall Bowers <me@maxdeviant.com>"]
repository = "https://github.com/maxdeviant/zed-code-stats"

[language_servers.code-stats-ls]
name = "Code::Stats LS"
languages = [
    "AsciiDoc",
    "Assembly",
    "Astro",
    "C",
    "C++",
    "Clojure",
    "Common Lisp",
    "Coq",
    "Crystal",
    "CSharp",
    "CSS",
    "CSV",
    "D",
    "Dart",
    "Diff",
    "Dockerfile",
    "Elixir",
    "Elm",
    "Erlang",
    "Fish",
    "FSharp",
    "GDScript",
    "Gleam",
    "GLSL",
    "Go",
    "GraphQL",
    "Haskell",
    "HEEX",
    "HTML",
    "Hy",
    "Idris",
    "Java",
    "JavaScript",
    "JSON",
    "JSONC",
    "Julia",
    "KDL",
    "Kotlin",
    "Lua",
    "Markdown",
    "Nickel",
    "Nim",
    "Nix",
    "OCaml",
    "Prolog",
    "PureScript",
    "Python",
    "Racket",
    "Roc",
    "Ruby",
    "Rust",
    "Scala",
    "Scheme",
    "SCSS",
    "Shell Script",
    "SQL",
    "Svelte",
    "Swift",
    "TOML",
    "TSX",
    "TypeScript",
    "Vue.js",
    "WGSL",
    "WIT",
    "XML",
    "YAML",
    "Zig",
]
